insert into suit (id, suit_name, color) values (1, 'Lang and Sons', 'Red');
insert into suit (id, suit_name, color) values (2, 'Barrows-Kozey', 'Pink');
insert into suit (id, suit_name, color) values (3, 'Rutherford, Corwin and Harber', 'Puce');
insert into suit (id, suit_name, color) values (4, 'Carroll LLC', 'Fuscia');
insert into suit (id, suit_name, color) values (5, 'Bradtke LLC', 'Violet');
insert into suit (id, suit_name, color) values (6, 'Walsh LLC', 'Orange');
insert into suit (id, suit_name, color) values (7, 'Schuppe Inc', 'Crimson');
insert into suit (id, suit_name, color) values (8, 'Raynor, Dickens and Rempel', 'Green');
insert into suit (id, suit_name, color) values (9, 'Kertzmann, Vandervort and Wiegand', 'Violet');
insert into suit (id, suit_name, color) values (10, 'O''Kon-Marquardt', 'Yellow');
insert into suit (id, suit_name, color) values (11, 'O''Kon-Thiel', 'Aquamarine');
insert into suit (id, suit_name, color) values (12, 'Hand Group', 'Turquoise');
insert into suit (id, suit_name, color) values (13, 'Mayert, Yost and Cassin', 'Khaki');
insert into suit (id, suit_name, color) values (14, 'Monahan Group', 'Teal');
insert into suit (id, suit_name, color) values (15, 'Corkery, Satterfield and Schmidt', 'Teal');
insert into suit (id, suit_name, color) values (16, 'Jones-Mosciski', 'Orange');
insert into suit (id, suit_name, color) values (17, 'Berge Group', 'Pink');
insert into suit (id, suit_name, color) values (18, 'Koch-Nikolaus', 'Aquamarine');
insert into suit (id, suit_name, color) values (19, 'Gusikowski Inc', 'Orange');
insert into suit (id, suit_name, color) values (20, 'Jacobson, Schmitt and Hoeger', 'Red');
insert into suit (id, suit_name, color) values (21, 'Cremin-Kutch', 'Purple');
insert into suit (id, suit_name, color) values (22, 'Brown, Wyman and Marks', 'Blue');
insert into suit (id, suit_name, color) values (23, 'Stokes Group', 'Teal');
insert into suit (id, suit_name, color) values (24, 'Pagac Inc', 'Green');
insert into suit (id, suit_name, color) values (25, 'Jenkins and Sons', 'Teal');
insert into suit (id, suit_name, color) values (26, 'Waters Group', 'Puce');
insert into suit (id, suit_name, color) values (27, 'Conn Inc', 'Khaki');
insert into suit (id, suit_name, color) values (28, 'Medhurst LLC', 'Goldenrod');
insert into suit (id, suit_name, color) values (29, 'Larkin Inc', 'Blue');
insert into suit (id, suit_name, color) values (30, 'Runolfsdottir-Kuhlman', 'Green');
insert into suit (id, suit_name, color) values (31, 'Morar LLC', 'Fuscia');
insert into suit (id, suit_name, color) values (32, 'Hartmann, Kozey and Lakin', 'Yellow');
insert into suit (id, suit_name, color) values (33, 'Bogan, Considine and Romaguera', 'Teal');
insert into suit (id, suit_name, color) values (34, 'Russel Inc', 'Orange');
insert into suit (id, suit_name, color) values (35, 'Lueilwitz-Collier', 'Puce');
insert into suit (id, suit_name, color) values (36, 'Balistreri Inc', 'Purple');
insert into suit (id, suit_name, color) values (37, 'Rodriguez-Weimann', 'Violet');
insert into suit (id, suit_name, color) values (38, 'Murray Group', 'Blue');
insert into suit (id, suit_name, color) values (39, 'Upton Group', 'Khaki');
insert into suit (id, suit_name, color) values (40, 'Orn, Durgan and Tremblay', 'Pink');
insert into suit (id, suit_name, color) values (41, 'Hessel LLC', 'Yellow');
insert into suit (id, suit_name, color) values (42, 'Schultz-Stehr', 'Khaki');
insert into suit (id, suit_name, color) values (43, 'Waelchi-Vandervort', 'Yellow');
insert into suit (id, suit_name, color) values (44, 'Reichel-Torphy', 'Purple');
insert into suit (id, suit_name, color) values (45, 'Hills and Sons', 'Puce');
insert into suit (id, suit_name, color) values (46, 'Harber-Kuphal', 'Puce');
insert into suit (id, suit_name, color) values (47, 'Gottlieb Group', 'Yellow');
insert into suit (id, suit_name, color) values (48, 'Conn LLC', 'Crimson');
insert into suit (id, suit_name, color) values (49, 'Nader LLC', 'Khaki');
insert into suit (id, suit_name, color) values (50, 'Little-Hettinger', 'Mauv');
insert into suit (id, suit_name, color) values (51, 'Schmidt-Heller', 'Goldenrod');
insert into suit (id, suit_name, color) values (52, 'Waters, Kling and Rolfson', 'Khaki');
insert into suit (id, suit_name, color) values (53, 'Boyer, Monahan and Gerlach', 'Mauv');
insert into suit (id, suit_name, color) values (54, 'Bergnaum, Pouros and Johnson', 'Yellow');
insert into suit (id, suit_name, color) values (55, 'Harris, Ortiz and Fahey', 'Mauv');
insert into suit (id, suit_name, color) values (56, 'Heathcote-Hegmann', 'Crimson');
insert into suit (id, suit_name, color) values (57, 'Smith-Abshire', 'Aquamarine');
insert into suit (id, suit_name, color) values (58, 'Watsica-Pfeffer', 'Puce');
insert into suit (id, suit_name, color) values (59, 'King and Sons', 'Teal');
insert into suit (id, suit_name, color) values (60, 'Von-Nicolas', 'Crimson');
insert into suit (id, suit_name, color) values (61, 'Bode-Kovacek', 'Mauv');
insert into suit (id, suit_name, color) values (62, 'Kling-Huel', 'Mauv');
insert into suit (id, suit_name, color) values (63, 'Doyle, Greenfelder and Larkin', 'Fuscia');
insert into suit (id, suit_name, color) values (64, 'Durgan, Kris and Dach', 'Crimson');
insert into suit (id, suit_name, color) values (65, 'Erdman-Schaden', 'Violet');
insert into suit (id, suit_name, color) values (66, 'Beer and Sons', 'Teal');
insert into suit (id, suit_name, color) values (67, 'Smith, Nitzsche and Willms', 'Purple');
insert into suit (id, suit_name, color) values (68, 'Cremin-Gibson', 'Crimson');
insert into suit (id, suit_name, color) values (69, 'Grimes and Sons', 'Blue');
insert into suit (id, suit_name, color) values (70, 'Simonis, Spinka and Davis', 'Indigo');
insert into suit (id, suit_name, color) values (71, 'Hoppe, Gottlieb and Marks', 'Green');
insert into suit (id, suit_name, color) values (72, 'Beahan Group', 'Goldenrod');
insert into suit (id, suit_name, color) values (73, 'Bechtelar and Sons', 'Purple');
insert into suit (id, suit_name, color) values (74, 'Will-Runte', 'Green');
insert into suit (id, suit_name, color) values (75, 'Jacobson Inc', 'Orange');
insert into suit (id, suit_name, color) values (76, 'Fritsch, Nienow and Balistreri', 'Orange');
insert into suit (id, suit_name, color) values (77, 'Howell, Ritchie and Rolfson', 'Pink');
insert into suit (id, suit_name, color) values (78, 'Jast, Frami and Stamm', 'Fuscia');
insert into suit (id, suit_name, color) values (79, 'Gleichner-Walter', 'Red');
insert into suit (id, suit_name, color) values (80, 'Carter and Sons', 'Green');
insert into suit (id, suit_name, color) values (81, 'Gaylord-Armstrong', 'Indigo');
insert into suit (id, suit_name, color) values (82, 'Mann-Wiegand', 'Goldenrod');
insert into suit (id, suit_name, color) values (83, 'Ratke, Fadel and Reilly', 'Aquamarine');
insert into suit (id, suit_name, color) values (84, 'Treutel Inc', 'Indigo');
insert into suit (id, suit_name, color) values (85, 'Johnson, Homenick and Schulist', 'Mauv');
insert into suit (id, suit_name, color) values (86, 'Klein-Hintz', 'Pink');
insert into suit (id, suit_name, color) values (87, 'Dach-MacGyver', 'Crimson');
insert into suit (id, suit_name, color) values (88, 'Dibbert and Sons', 'Blue');
insert into suit (id, suit_name, color) values (89, 'Cole, Keebler and Grant', 'Indigo');
insert into suit (id, suit_name, color) values (90, 'O''Reilly, Metz and Miller', 'Purple');
insert into suit (id, suit_name, color) values (91, 'Heidenreich Inc', 'Maroon');
insert into suit (id, suit_name, color) values (92, 'Haley Group', 'Mauv');
insert into suit (id, suit_name, color) values (93, 'Gulgowski, Bauch and Considine', 'Blue');
insert into suit (id, suit_name, color) values (94, 'McDermott Inc', 'Goldenrod');
insert into suit (id, suit_name, color) values (95, 'Rowe Group', 'Violet');
insert into suit (id, suit_name, color) values (96, 'Cormier, Swift and Ondricka', 'Pink');
insert into suit (id, suit_name, color) values (97, 'Bradtke, Wiegand and Schaden', 'Red');
insert into suit (id, suit_name, color) values (98, 'Zboncak Inc', 'Puce');
insert into suit (id, suit_name, color) values (99, 'Morissette, Nolan and Kozey', 'Pink');
insert into suit (id, suit_name, color) values (100, 'Keebler, Flatley and McGlynn', 'Turquoise');
insert into suit (id, suit_name, color) values (101, 'Leannon Group', 'Fuscia');
insert into suit (id, suit_name, color) values (102, 'Luettgen, Daugherty and Berge', 'Blue');
insert into suit (id, suit_name, color) values (103, 'Wintheiser-Crooks', 'Red');
insert into suit (id, suit_name, color) values (104, 'Buckridge Group', 'Turquoise');
insert into suit (id, suit_name, color) values (105, 'Schulist LLC', 'Puce');
insert into suit (id, suit_name, color) values (106, 'Cruickshank, Ankunding and Hilpert', 'Goldenrod');
insert into suit (id, suit_name, color) values (107, 'Romaguera, Skiles and Keebler', 'Khaki');
insert into suit (id, suit_name, color) values (108, 'Toy-Schmitt', 'Turquoise');
insert into suit (id, suit_name, color) values (109, 'Hyatt-Tromp', 'Purple');
insert into suit (id, suit_name, color) values (110, 'Brown-Bednar', 'Green');
insert into suit (id, suit_name, color) values (111, 'Boehm Group', 'Crimson');
insert into suit (id, suit_name, color) values (112, 'Senger, Fay and Skiles', 'Mauv');
insert into suit (id, suit_name, color) values (113, 'Crooks LLC', 'Crimson');
insert into suit (id, suit_name, color) values (114, 'O''Reilly-Heathcote', 'Goldenrod');
insert into suit (id, suit_name, color) values (115, 'Spinka, Botsford and Stanton', 'Green');
insert into suit (id, suit_name, color) values (116, 'Kulas, Schimmel and Rowe', 'Mauv');
insert into suit (id, suit_name, color) values (117, 'Grimes, Rolfson and Wintheiser', 'Puce');
insert into suit (id, suit_name, color) values (118, 'Carroll Inc', 'Mauv');
insert into suit (id, suit_name, color) values (119, 'DuBuque-Marvin', 'Maroon');
insert into suit (id, suit_name, color) values (120, 'Wiegand, Runolfsson and Corwin', 'Green');
insert into suit (id, suit_name, color) values (121, 'McCullough and Sons', 'Teal');
insert into suit (id, suit_name, color) values (122, 'Hoeger Group', 'Purple');
insert into suit (id, suit_name, color) values (123, 'Kreiger Group', 'Khaki');
insert into suit (id, suit_name, color) values (124, 'Ward Inc', 'Puce');
insert into suit (id, suit_name, color) values (125, 'Stanton, Kunze and Dietrich', 'Goldenrod');
insert into suit (id, suit_name, color) values (126, 'Hand and Sons', 'Crimson');
insert into suit (id, suit_name, color) values (127, 'D''Amore Inc', 'Puce');
insert into suit (id, suit_name, color) values (128, 'Wisozk-Hills', 'Crimson');
insert into suit (id, suit_name, color) values (129, 'Crooks-Blanda', 'Goldenrod');
insert into suit (id, suit_name, color) values (130, 'Tremblay-Turner', 'Violet');
insert into suit (id, suit_name, color) values (131, 'Miller Inc', 'Puce');
insert into suit (id, suit_name, color) values (132, 'Hirthe Inc', 'Red');
insert into suit (id, suit_name, color) values (133, 'McCullough Group', 'Red');
insert into suit (id, suit_name, color) values (134, 'Cronin-Willms', 'Puce');
insert into suit (id, suit_name, color) values (135, 'Gaylord-Hermann', 'Red');
insert into suit (id, suit_name, color) values (136, 'Ledner and Sons', 'Purple');
insert into suit (id, suit_name, color) values (137, 'Dickens and Sons', 'Green');
insert into suit (id, suit_name, color) values (138, 'Schroeder-Mueller', 'Teal');
insert into suit (id, suit_name, color) values (139, 'Flatley-Russel', 'Mauv');
insert into suit (id, suit_name, color) values (140, 'Lowe-Kshlerin', 'Puce');
insert into suit (id, suit_name, color) values (141, 'Kerluke-Wyman', 'Maroon');
insert into suit (id, suit_name, color) values (142, 'Ward, Mertz and Howe', 'Yellow');
insert into suit (id, suit_name, color) values (143, 'Carter-Boyer', 'Puce');
insert into suit (id, suit_name, color) values (144, 'Hintz-Cassin', 'Yellow');
insert into suit (id, suit_name, color) values (145, 'Hickle-Little', 'Maroon');
insert into suit (id, suit_name, color) values (146, 'Jakubowski, Reichel and Balistreri', 'Green');
insert into suit (id, suit_name, color) values (147, 'Orn, Glover and Klocko', 'Violet');
insert into suit (id, suit_name, color) values (148, 'Reilly-Breitenberg', 'Red');
insert into suit (id, suit_name, color) values (149, 'Schaefer Inc', 'Yellow');
insert into suit (id, suit_name, color) values (150, 'Flatley LLC', 'Fuscia');
insert into suit (id, suit_name, color) values (151, 'Schinner Group', 'Khaki');
insert into suit (id, suit_name, color) values (152, 'Von-Considine', 'Indigo');
insert into suit (id, suit_name, color) values (153, 'Turcotte-Bergnaum', 'Teal');
insert into suit (id, suit_name, color) values (154, 'Murray-Reynolds', 'Red');
insert into suit (id, suit_name, color) values (155, 'Kemmer Group', 'Turquoise');
insert into suit (id, suit_name, color) values (156, 'Upton-Conn', 'Green');
insert into suit (id, suit_name, color) values (157, 'Kuhlman, Medhurst and Wiza', 'Purple');
insert into suit (id, suit_name, color) values (158, 'Frami-Toy', 'Pink');
insert into suit (id, suit_name, color) values (159, 'Mann Inc', 'Khaki');
insert into suit (id, suit_name, color) values (160, 'Rowe-Hickle', 'Yellow');
insert into suit (id, suit_name, color) values (161, 'Morissette-Prohaska', 'Khaki');
insert into suit (id, suit_name, color) values (162, 'Boyle, Kautzer and Watsica', 'Goldenrod');
insert into suit (id, suit_name, color) values (163, 'Pouros Group', 'Crimson');
insert into suit (id, suit_name, color) values (164, 'Walker, Stanton and Daniel', 'Teal');
insert into suit (id, suit_name, color) values (165, 'Haley-Walker', 'Violet');
insert into suit (id, suit_name, color) values (166, 'Schinner, Gottlieb and Kuhn', 'Red');
insert into suit (id, suit_name, color) values (167, 'Bernier and Sons', 'Orange');
insert into suit (id, suit_name, color) values (168, 'Mante-Klein', 'Pink');
insert into suit (id, suit_name, color) values (169, 'Denesik, Kuhlman and Kilback', 'Fuscia');
insert into suit (id, suit_name, color) values (170, 'Cronin, Zboncak and Gleichner', 'Pink');
insert into suit (id, suit_name, color) values (171, 'Schuster-Cronin', 'Purple');
insert into suit (id, suit_name, color) values (172, 'Brakus, Schneider and Schultz', 'Puce');
insert into suit (id, suit_name, color) values (173, 'Hagenes-Gaylord', 'Blue');
insert into suit (id, suit_name, color) values (174, 'Quigley-Effertz', 'Maroon');
insert into suit (id, suit_name, color) values (175, 'Mosciski Group', 'Purple');
insert into suit (id, suit_name, color) values (176, 'Hartmann LLC', 'Indigo');
insert into suit (id, suit_name, color) values (177, 'Gutmann, Wuckert and Buckridge', 'Pink');
insert into suit (id, suit_name, color) values (178, 'Beier-Lebsack', 'Teal');
insert into suit (id, suit_name, color) values (179, 'Murazik Group', 'Pink');
insert into suit (id, suit_name, color) values (180, 'Howell LLC', 'Indigo');
insert into suit (id, suit_name, color) values (181, 'Davis-Wolff', 'Yellow');
insert into suit (id, suit_name, color) values (182, 'Spinka Group', 'Red');
insert into suit (id, suit_name, color) values (183, 'Miller Inc', 'Purple');
insert into suit (id, suit_name, color) values (184, 'Schumm-Sawayn', 'Yellow');
insert into suit (id, suit_name, color) values (185, 'Waters Group', 'Fuscia');
insert into suit (id, suit_name, color) values (186, 'Daugherty-Wiza', 'Aquamarine');
insert into suit (id, suit_name, color) values (187, 'Huels, Lakin and McDermott', 'Goldenrod');
insert into suit (id, suit_name, color) values (188, 'Hoeger Inc', 'Khaki');
insert into suit (id, suit_name, color) values (189, 'Mills and Sons', 'Violet');
insert into suit (id, suit_name, color) values (190, 'Thiel Group', 'Teal');
insert into suit (id, suit_name, color) values (191, 'Braun, Stroman and Graham', 'Purple');
insert into suit (id, suit_name, color) values (192, 'Hodkiewicz-Tremblay', 'Yellow');
insert into suit (id, suit_name, color) values (193, 'Berge and Sons', 'Yellow');
insert into suit (id, suit_name, color) values (194, 'Goyette-Erdman', 'Puce');
insert into suit (id, suit_name, color) values (195, 'Prohaska, Wyman and Strosin', 'Fuscia');
insert into suit (id, suit_name, color) values (196, 'Kulas-Beier', 'Orange');
insert into suit (id, suit_name, color) values (197, 'D''Amore, Koch and Halvorson', 'Fuscia');
insert into suit (id, suit_name, color) values (198, 'Conroy, Hodkiewicz and Larson', 'Aquamarine');
insert into suit (id, suit_name, color) values (199, 'Brakus-Schultz', 'Red');
insert into suit (id, suit_name, color) values (200, 'Fadel Inc', 'Goldenrod');
insert into suit (id, suit_name, color) values (201, 'O''Reilly Inc', 'Red');
insert into suit (id, suit_name, color) values (202, 'Morissette Group', 'Turquoise');
insert into suit (id, suit_name, color) values (203, 'Funk-Daniel', 'Violet');
insert into suit (id, suit_name, color) values (204, 'Bednar-Hintz', 'Yellow');
insert into suit (id, suit_name, color) values (205, 'Schuster, Connelly and Auer', 'Puce');
insert into suit (id, suit_name, color) values (206, 'Kihn, Reichel and Hand', 'Fuscia');
insert into suit (id, suit_name, color) values (207, 'Fadel Group', 'Violet');
insert into suit (id, suit_name, color) values (208, 'Yost, Weimann and Stanton', 'Mauv');
insert into suit (id, suit_name, color) values (209, 'Gerlach, Heller and Rempel', 'Mauv');
insert into suit (id, suit_name, color) values (210, 'Reilly Group', 'Indigo');
insert into suit (id, suit_name, color) values (211, 'Gutmann, Swaniawski and Feeney', 'Maroon');
insert into suit (id, suit_name, color) values (212, 'Steuber, Stamm and Mohr', 'Red');
insert into suit (id, suit_name, color) values (213, 'Keeling Group', 'Orange');
insert into suit (id, suit_name, color) values (214, 'Gibson, Maggio and Metz', 'Aquamarine');
insert into suit (id, suit_name, color) values (215, 'Heathcote Group', 'Goldenrod');
insert into suit (id, suit_name, color) values (216, 'White, Bahringer and Gutmann', 'Puce');
insert into suit (id, suit_name, color) values (217, 'Jaskolski, Jaskolski and Gerlach', 'Khaki');
insert into suit (id, suit_name, color) values (218, 'Stroman and Sons', 'Crimson');
insert into suit (id, suit_name, color) values (219, 'Hansen-Vandervort', 'Goldenrod');
insert into suit (id, suit_name, color) values (220, 'Welch, Fay and Walter', 'Indigo');
insert into suit (id, suit_name, color) values (221, 'Lynch-Goldner', 'Violet');
insert into suit (id, suit_name, color) values (222, 'Cronin Inc', 'Violet');
insert into suit (id, suit_name, color) values (223, 'Greenholt, Collins and Kiehn', 'Green');
insert into suit (id, suit_name, color) values (224, 'Legros-Morissette', 'Fuscia');
insert into suit (id, suit_name, color) values (225, 'Jacobson-Nikolaus', 'Violet');
insert into suit (id, suit_name, color) values (226, 'Nienow, Kulas and Rutherford', 'Purple');
insert into suit (id, suit_name, color) values (227, 'Wiegand-Howell', 'Turquoise');
insert into suit (id, suit_name, color) values (228, 'Volkman Inc', 'Maroon');
insert into suit (id, suit_name, color) values (229, 'Predovic-Franecki', 'Turquoise');
insert into suit (id, suit_name, color) values (230, 'Streich-Little', 'Mauv');
insert into suit (id, suit_name, color) values (231, 'McClure Inc', 'Indigo');
insert into suit (id, suit_name, color) values (232, 'Armstrong Inc', 'Indigo');
insert into suit (id, suit_name, color) values (233, 'Feest, Willms and Walsh', 'Purple');
insert into suit (id, suit_name, color) values (234, 'Stokes, Ebert and Rippin', 'Maroon');
insert into suit (id, suit_name, color) values (235, 'Turner, Marks and Zieme', 'Aquamarine');
insert into suit (id, suit_name, color) values (236, 'Lesch-Price', 'Pink');
insert into suit (id, suit_name, color) values (237, 'Koepp, Hane and Cole', 'Turquoise');
insert into suit (id, suit_name, color) values (238, 'Mitchell, Howell and Kuhn', 'Mauv');
insert into suit (id, suit_name, color) values (239, 'Jacobi, Volkman and Nicolas', 'Aquamarine');
insert into suit (id, suit_name, color) values (240, 'Robel LLC', 'Purple');
insert into suit (id, suit_name, color) values (241, 'Ritchie-Sanford', 'Fuscia');
insert into suit (id, suit_name, color) values (242, 'Beier, Franecki and Abernathy', 'Purple');
insert into suit (id, suit_name, color) values (243, 'Witting-Wilderman', 'Turquoise');
insert into suit (id, suit_name, color) values (244, 'Johnston LLC', 'Violet');
insert into suit (id, suit_name, color) values (245, 'Mante LLC', 'Indigo');
insert into suit (id, suit_name, color) values (246, 'Lowe-Feest', 'Green');
insert into suit (id, suit_name, color) values (247, 'Robel Group', 'Blue');
insert into suit (id, suit_name, color) values (248, 'O''Hara-Wehner', 'Maroon');
insert into suit (id, suit_name, color) values (249, 'Moore-Conn', 'Indigo');
insert into suit (id, suit_name, color) values (250, 'Powlowski Group', 'Red');
insert into suit (id, suit_name, color) values (251, 'Hills Group', 'Yellow');
insert into suit (id, suit_name, color) values (252, 'Runolfsdottir-Davis', 'Crimson');
insert into suit (id, suit_name, color) values (253, 'Yost, Sawayn and Lindgren', 'Puce');
insert into suit (id, suit_name, color) values (254, 'Lockman-Boyer', 'Fuscia');
insert into suit (id, suit_name, color) values (255, 'Runolfsson, Satterfield and Graham', 'Teal');
insert into suit (id, suit_name, color) values (256, 'Nicolas, Kutch and Waters', 'Turquoise');
insert into suit (id, suit_name, color) values (257, 'Koepp-Douglas', 'Green');
insert into suit (id, suit_name, color) values (258, 'Ankunding, Watsica and Conn', 'Goldenrod');
insert into suit (id, suit_name, color) values (259, 'Batz, Goldner and Haley', 'Blue');
insert into suit (id, suit_name, color) values (260, 'Quitzon-Osinski', 'Khaki');
insert into suit (id, suit_name, color) values (261, 'Rippin Inc', 'Purple');
insert into suit (id, suit_name, color) values (262, 'Berge-Bergnaum', 'Red');
insert into suit (id, suit_name, color) values (263, 'Ledner-Littel', 'Yellow');
insert into suit (id, suit_name, color) values (264, 'Morar-Bernier', 'Puce');
insert into suit (id, suit_name, color) values (265, 'Cartwright-Keebler', 'Pink');
insert into suit (id, suit_name, color) values (266, 'Larson Group', 'Aquamarine');
insert into suit (id, suit_name, color) values (267, 'Bartell-Hane', 'Aquamarine');
insert into suit (id, suit_name, color) values (268, 'Watsica, Bartell and Stokes', 'Blue');
insert into suit (id, suit_name, color) values (269, 'Schneider-Runte', 'Mauv');
insert into suit (id, suit_name, color) values (270, 'Powlowski Group', 'Maroon');
insert into suit (id, suit_name, color) values (271, 'Hyatt, Green and Effertz', 'Fuscia');
insert into suit (id, suit_name, color) values (272, 'Haley, Bergnaum and Macejkovic', 'Violet');
insert into suit (id, suit_name, color) values (273, 'Upton-Bailey', 'Maroon');
insert into suit (id, suit_name, color) values (274, 'Armstrong Inc', 'Turquoise');
insert into suit (id, suit_name, color) values (275, 'Moen, Williamson and Marquardt', 'Aquamarine');
insert into suit (id, suit_name, color) values (276, 'Kovacek LLC', 'Green');
insert into suit (id, suit_name, color) values (277, 'Fadel-Torp', 'Teal');
insert into suit (id, suit_name, color) values (278, 'Barton, Smitham and Harvey', 'Blue');
insert into suit (id, suit_name, color) values (279, 'Harris-Glover', 'Aquamarine');
insert into suit (id, suit_name, color) values (280, 'Jacobson, Abshire and Morar', 'Purple');
insert into suit (id, suit_name, color) values (281, 'Wisozk-Vandervort', 'Pink');
insert into suit (id, suit_name, color) values (282, 'Purdy, Hyatt and Senger', 'Purple');
insert into suit (id, suit_name, color) values (283, 'Tillman Inc', 'Khaki');
insert into suit (id, suit_name, color) values (284, 'Schuppe, Stokes and Brakus', 'Aquamarine');
insert into suit (id, suit_name, color) values (285, 'Grady-Kihn', 'Green');
insert into suit (id, suit_name, color) values (286, 'Grant LLC', 'Goldenrod');
insert into suit (id, suit_name, color) values (287, 'Mohr, Boehm and MacGyver', 'Orange');
insert into suit (id, suit_name, color) values (288, 'Dare-Kautzer', 'Violet');
insert into suit (id, suit_name, color) values (289, 'King-Metz', 'Blue');
insert into suit (id, suit_name, color) values (290, 'Kunde Inc', 'Indigo');
insert into suit (id, suit_name, color) values (291, 'Predovic, Trantow and McDermott', 'Fuscia');
insert into suit (id, suit_name, color) values (292, 'Wilderman Group', 'Puce');
insert into suit (id, suit_name, color) values (293, 'Lakin-Fahey', 'Aquamarine');
insert into suit (id, suit_name, color) values (294, 'Kihn, Wilderman and Quitzon', 'Khaki');
insert into suit (id, suit_name, color) values (295, 'Harris-Schmidt', 'Pink');
insert into suit (id, suit_name, color) values (296, 'Yost-Parisian', 'Turquoise');
insert into suit (id, suit_name, color) values (297, 'Orn, Klocko and Wehner', 'Red');
insert into suit (id, suit_name, color) values (298, 'Baumbach-Medhurst', 'Maroon');
insert into suit (id, suit_name, color) values (299, 'Feest and Sons', 'Blue');
insert into suit (id, suit_name, color) values (300, 'Boyer LLC', 'Fuscia');
insert into suit (id, suit_name, color) values (301, 'Ledner-Ondricka', 'Orange');
insert into suit (id, suit_name, color) values (302, 'Stokes, Lockman and Abernathy', 'Goldenrod');
insert into suit (id, suit_name, color) values (303, 'Rowe, Bashirian and Rutherford', 'Maroon');
insert into suit (id, suit_name, color) values (304, 'Hamill, West and Hoppe', 'Crimson');
insert into suit (id, suit_name, color) values (305, 'Ullrich, Runolfsson and Lueilwitz', 'Crimson');
insert into suit (id, suit_name, color) values (306, 'Rowe, Walsh and Trantow', 'Blue');
insert into suit (id, suit_name, color) values (307, 'Kulas-Armstrong', 'Pink');
insert into suit (id, suit_name, color) values (308, 'Streich and Sons', 'Turquoise');
insert into suit (id, suit_name, color) values (309, 'Walker-Hoppe', 'Puce');
insert into suit (id, suit_name, color) values (310, 'Langosh-Purdy', 'Teal');
insert into suit (id, suit_name, color) values (311, 'Goyette, Crooks and Wiegand', 'Red');
insert into suit (id, suit_name, color) values (312, 'Roberts LLC', 'Indigo');
insert into suit (id, suit_name, color) values (313, 'Harber, Hayes and Lindgren', 'Turquoise');
insert into suit (id, suit_name, color) values (314, 'Raynor LLC', 'Indigo');
insert into suit (id, suit_name, color) values (315, 'Sawayn and Sons', 'Indigo');
insert into suit (id, suit_name, color) values (316, 'Flatley, Green and Wilkinson', 'Orange');
insert into suit (id, suit_name, color) values (317, 'Wisoky, Bernier and Purdy', 'Aquamarine');
insert into suit (id, suit_name, color) values (318, 'Friesen, Kemmer and Lakin', 'Pink');
insert into suit (id, suit_name, color) values (319, 'Gutkowski and Sons', 'Red');
insert into suit (id, suit_name, color) values (320, 'Tillman, Gutmann and Ferry', 'Mauv');
insert into suit (id, suit_name, color) values (321, 'Heller, Conn and Moore', 'Red');
insert into suit (id, suit_name, color) values (322, 'Lynch, Roberts and Little', 'Green');
insert into suit (id, suit_name, color) values (323, 'Heaney-Emard', 'Indigo');
insert into suit (id, suit_name, color) values (324, 'Rodriguez LLC', 'Khaki');
insert into suit (id, suit_name, color) values (325, 'Nitzsche LLC', 'Fuscia');
insert into suit (id, suit_name, color) values (326, 'Pfannerstill and Sons', 'Red');
insert into suit (id, suit_name, color) values (327, 'Koch, Pfeffer and Cartwright', 'Pink');
insert into suit (id, suit_name, color) values (328, 'Willms and Sons', 'Purple');
insert into suit (id, suit_name, color) values (329, 'Boehm LLC', 'Turquoise');
insert into suit (id, suit_name, color) values (330, 'Cummings-Hessel', 'Crimson');
insert into suit (id, suit_name, color) values (331, 'Stamm-Kuhn', 'Fuscia');
insert into suit (id, suit_name, color) values (332, 'Kozey Inc', 'Turquoise');
insert into suit (id, suit_name, color) values (333, 'Bartell Inc', 'Khaki');
insert into suit (id, suit_name, color) values (334, 'Sawayn, Langworth and Orn', 'Yellow');
insert into suit (id, suit_name, color) values (335, 'Beahan-Koss', 'Mauv');
insert into suit (id, suit_name, color) values (336, 'Sanford Inc', 'Orange');
insert into suit (id, suit_name, color) values (337, 'O''Kon-Nader', 'Orange');
insert into suit (id, suit_name, color) values (338, 'Kovacek-Hessel', 'Indigo');
insert into suit (id, suit_name, color) values (339, 'Kutch, Bailey and Dietrich', 'Puce');
insert into suit (id, suit_name, color) values (340, 'Kuhlman, McGlynn and Hyatt', 'Aquamarine');
insert into suit (id, suit_name, color) values (341, 'Barton-Wyman', 'Mauv');
insert into suit (id, suit_name, color) values (342, 'Von-Hegmann', 'Red');
insert into suit (id, suit_name, color) values (343, 'Bahringer Group', 'Blue');
insert into suit (id, suit_name, color) values (344, 'Hartmann-Huel', 'Indigo');
insert into suit (id, suit_name, color) values (345, 'Gusikowski, Auer and Thiel', 'Orange');
insert into suit (id, suit_name, color) values (346, 'Ward-Oberbrunner', 'Blue');
insert into suit (id, suit_name, color) values (347, 'Buckridge, Haag and Crona', 'Yellow');
insert into suit (id, suit_name, color) values (348, 'Torphy Inc', 'Teal');
insert into suit (id, suit_name, color) values (349, 'Block-Frami', 'Yellow');
insert into suit (id, suit_name, color) values (350, 'Feest, O''Keefe and Hammes', 'Purple');
insert into suit (id, suit_name, color) values (351, 'Zboncak, Douglas and Heathcote', 'Pink');
insert into suit (id, suit_name, color) values (352, 'Blanda Inc', 'Khaki');
insert into suit (id, suit_name, color) values (353, 'Koepp, Rath and Predovic', 'Orange');
insert into suit (id, suit_name, color) values (354, 'Streich and Sons', 'Purple');
insert into suit (id, suit_name, color) values (355, 'Hudson-Ryan', 'Purple');
insert into suit (id, suit_name, color) values (356, 'Keebler, Turcotte and Ritchie', 'Crimson');
insert into suit (id, suit_name, color) values (357, 'Zieme and Sons', 'Fuscia');
insert into suit (id, suit_name, color) values (358, 'Moen Inc', 'Mauv');
insert into suit (id, suit_name, color) values (359, 'Runolfsson-Legros', 'Indigo');
insert into suit (id, suit_name, color) values (360, 'Larkin-Harris', 'Goldenrod');
insert into suit (id, suit_name, color) values (361, 'Gutmann Group', 'Crimson');
insert into suit (id, suit_name, color) values (362, 'Haag-Nicolas', 'Teal');
insert into suit (id, suit_name, color) values (363, 'Macejkovic-Christiansen', 'Pink');
insert into suit (id, suit_name, color) values (364, 'MacGyver-Krajcik', 'Blue');
insert into suit (id, suit_name, color) values (365, 'Sanford, Kuphal and Wilderman', 'Indigo');
insert into suit (id, suit_name, color) values (366, 'Denesik-Walker', 'Crimson');
insert into suit (id, suit_name, color) values (367, 'Hammes Group', 'Khaki');
insert into suit (id, suit_name, color) values (368, 'Anderson LLC', 'Mauv');
insert into suit (id, suit_name, color) values (369, 'Graham, McLaughlin and Borer', 'Puce');
insert into suit (id, suit_name, color) values (370, 'Steuber, Ernser and Paucek', 'Green');
insert into suit (id, suit_name, color) values (371, 'Bins, Parker and Kihn', 'Crimson');
insert into suit (id, suit_name, color) values (372, 'Torphy, Schultz and Kemmer', 'Blue');
insert into suit (id, suit_name, color) values (373, 'Smitham, Pagac and Donnelly', 'Crimson');
insert into suit (id, suit_name, color) values (374, 'Goyette-Kshlerin', 'Purple');
insert into suit (id, suit_name, color) values (375, 'Muller-Carroll', 'Maroon');
insert into suit (id, suit_name, color) values (376, 'Mayert-Leannon', 'Pink');
insert into suit (id, suit_name, color) values (377, 'Kuhn-Lang', 'Fuscia');
insert into suit (id, suit_name, color) values (378, 'Haley LLC', 'Indigo');
insert into suit (id, suit_name, color) values (379, 'Hettinger and Sons', 'Green');
insert into suit (id, suit_name, color) values (380, 'Hoeger-Koepp', 'Indigo');
insert into suit (id, suit_name, color) values (381, 'Brakus-Koss', 'Indigo');
insert into suit (id, suit_name, color) values (382, 'Schmidt Inc', 'Indigo');
insert into suit (id, suit_name, color) values (383, 'Lebsack-Runte', 'Puce');
insert into suit (id, suit_name, color) values (384, 'Crist, Fritsch and Corwin', 'Pink');
insert into suit (id, suit_name, color) values (385, 'Batz LLC', 'Teal');
insert into suit (id, suit_name, color) values (386, 'Watsica, Trantow and Kassulke', 'Aquamarine');
insert into suit (id, suit_name, color) values (387, 'Ziemann, Bednar and Kessler', 'Indigo');
insert into suit (id, suit_name, color) values (388, 'McCullough Group', 'Indigo');
insert into suit (id, suit_name, color) values (389, 'Keeling, Gottlieb and Reichel', 'Puce');
insert into suit (id, suit_name, color) values (390, 'Herzog-Cassin', 'Turquoise');
insert into suit (id, suit_name, color) values (391, 'Purdy and Sons', 'Maroon');
insert into suit (id, suit_name, color) values (392, 'Bogisich Inc', 'Mauv');
insert into suit (id, suit_name, color) values (393, 'Reichert and Sons', 'Indigo');
insert into suit (id, suit_name, color) values (394, 'Lindgren-Wisozk', 'Orange');
insert into suit (id, suit_name, color) values (395, 'Gusikowski Group', 'Teal');
insert into suit (id, suit_name, color) values (396, 'Davis-Feeney', 'Indigo');
insert into suit (id, suit_name, color) values (397, 'Prohaska-Yundt', 'Green');
insert into suit (id, suit_name, color) values (398, 'Gorczany-Becker', 'Red');
insert into suit (id, suit_name, color) values (399, 'Lubowitz and Sons', 'Puce');
insert into suit (id, suit_name, color) values (400, 'Simonis, Heathcote and Ryan', 'Fuscia');
insert into suit (id, suit_name, color) values (401, 'Cruickshank, Dach and Leuschke', 'Khaki');
insert into suit (id, suit_name, color) values (402, 'Nienow, Dibbert and Casper', 'Maroon');
insert into suit (id, suit_name, color) values (403, 'Schumm Inc', 'Pink');
insert into suit (id, suit_name, color) values (404, 'Little, Corwin and Hirthe', 'Violet');
insert into suit (id, suit_name, color) values (405, 'Bahringer, Fritsch and Quigley', 'Puce');
insert into suit (id, suit_name, color) values (406, 'Rolfson-Kunze', 'Aquamarine');
insert into suit (id, suit_name, color) values (407, 'Champlin LLC', 'Teal');
insert into suit (id, suit_name, color) values (408, 'Bednar-Yost', 'Khaki');
insert into suit (id, suit_name, color) values (409, 'Johnston-Rosenbaum', 'Khaki');
insert into suit (id, suit_name, color) values (410, 'Lesch-Predovic', 'Mauv');
insert into suit (id, suit_name, color) values (411, 'Ratke-Jerde', 'Turquoise');
insert into suit (id, suit_name, color) values (412, 'Turcotte-Kutch', 'Pink');
insert into suit (id, suit_name, color) values (413, 'Boyle-Dibbert', 'Turquoise');
insert into suit (id, suit_name, color) values (414, 'Stoltenberg, Gusikowski and Brakus', 'Goldenrod');
insert into suit (id, suit_name, color) values (415, 'Vandervort, Armstrong and Strosin', 'Mauv');
insert into suit (id, suit_name, color) values (416, 'Orn, Kiehn and Langworth', 'Violet');
insert into suit (id, suit_name, color) values (417, 'Hodkiewicz, Murphy and Hessel', 'Mauv');
insert into suit (id, suit_name, color) values (418, 'Schaefer, Sauer and Senger', 'Goldenrod');
insert into suit (id, suit_name, color) values (419, 'Bednar-Lesch', 'Goldenrod');
insert into suit (id, suit_name, color) values (420, 'Terry, Abernathy and Stiedemann', 'Maroon');
insert into suit (id, suit_name, color) values (421, 'Kuhic-Fay', 'Orange');
insert into suit (id, suit_name, color) values (422, 'Kling Inc', 'Violet');
insert into suit (id, suit_name, color) values (423, 'Waelchi, Parisian and Marvin', 'Yellow');
insert into suit (id, suit_name, color) values (424, 'Metz Group', 'Green');
insert into suit (id, suit_name, color) values (425, 'Bogan, Leannon and Dietrich', 'Goldenrod');
insert into suit (id, suit_name, color) values (426, 'Koelpin, Keeling and Trantow', 'Aquamarine');
insert into suit (id, suit_name, color) values (427, 'Lockman-Jacobs', 'Yellow');
insert into suit (id, suit_name, color) values (428, 'Anderson LLC', 'Puce');
insert into suit (id, suit_name, color) values (429, 'Cummings, Kuvalis and Schaden', 'Pink');
insert into suit (id, suit_name, color) values (430, 'Heller-Brakus', 'Indigo');
insert into suit (id, suit_name, color) values (431, 'Lebsack Inc', 'Khaki');
insert into suit (id, suit_name, color) values (432, 'Bins, Mosciski and McClure', 'Yellow');
insert into suit (id, suit_name, color) values (433, 'White, Gleason and Brakus', 'Red');
insert into suit (id, suit_name, color) values (434, 'Brown and Sons', 'Red');
insert into suit (id, suit_name, color) values (435, 'Romaguera Inc', 'Orange');
insert into suit (id, suit_name, color) values (436, 'Bergstrom LLC', 'Mauv');
insert into suit (id, suit_name, color) values (437, 'King, Ankunding and Abernathy', 'Orange');
insert into suit (id, suit_name, color) values (438, 'Lakin, Lueilwitz and Buckridge', 'Pink');
insert into suit (id, suit_name, color) values (439, 'O''Reilly, Dietrich and Huels', 'Purple');
insert into suit (id, suit_name, color) values (440, 'Thompson-Wiegand', 'Green');
insert into suit (id, suit_name, color) values (441, 'Bailey and Sons', 'Goldenrod');
insert into suit (id, suit_name, color) values (442, 'Glover and Sons', 'Orange');
insert into suit (id, suit_name, color) values (443, 'Botsford-Brekke', 'Puce');
insert into suit (id, suit_name, color) values (444, 'Dach-Weissnat', 'Turquoise');
insert into suit (id, suit_name, color) values (445, 'Friesen, Vandervort and Treutel', 'Red');
insert into suit (id, suit_name, color) values (446, 'Hickle LLC', 'Mauv');
insert into suit (id, suit_name, color) values (447, 'O''Conner LLC', 'Red');
insert into suit (id, suit_name, color) values (448, 'Spencer-Schultz', 'Violet');
insert into suit (id, suit_name, color) values (449, 'Beahan LLC', 'Puce');
insert into suit (id, suit_name, color) values (450, 'Grant Group', 'Khaki');
insert into suit (id, suit_name, color) values (451, 'Towne LLC', 'Crimson');
insert into suit (id, suit_name, color) values (452, 'Ebert, Toy and Klocko', 'Goldenrod');
insert into suit (id, suit_name, color) values (453, 'Connelly, Huel and Bogan', 'Blue');
insert into suit (id, suit_name, color) values (454, 'Tremblay, Brekke and Sanford', 'Indigo');
insert into suit (id, suit_name, color) values (455, 'Bechtelar-Doyle', 'Indigo');
insert into suit (id, suit_name, color) values (456, 'Schmitt Group', 'Indigo');
insert into suit (id, suit_name, color) values (457, 'Schinner and Sons', 'Violet');
insert into suit (id, suit_name, color) values (458, 'Beier, Rempel and Keeling', 'Violet');
insert into suit (id, suit_name, color) values (459, 'Schultz, Kuhlman and Metz', 'Khaki');
insert into suit (id, suit_name, color) values (460, 'Runolfsson-Bartoletti', 'Red');
insert into suit (id, suit_name, color) values (461, 'Kilback LLC', 'Maroon');
insert into suit (id, suit_name, color) values (462, 'Okuneva-Botsford', 'Red');
insert into suit (id, suit_name, color) values (463, 'Balistreri, Quitzon and Schuppe', 'Puce');
insert into suit (id, suit_name, color) values (464, 'Langosh-McCullough', 'Turquoise');
insert into suit (id, suit_name, color) values (465, 'Lowe-Greenholt', 'Blue');
insert into suit (id, suit_name, color) values (466, 'Hirthe and Sons', 'Pink');
insert into suit (id, suit_name, color) values (467, 'Marquardt-Mueller', 'Maroon');
insert into suit (id, suit_name, color) values (468, 'Rogahn, Zulauf and Langworth', 'Green');
insert into suit (id, suit_name, color) values (469, 'Brakus and Sons', 'Khaki');
insert into suit (id, suit_name, color) values (470, 'Renner Group', 'Teal');
insert into suit (id, suit_name, color) values (471, 'Kerluke-Feil', 'Pink');
insert into suit (id, suit_name, color) values (472, 'Stoltenberg and Sons', 'Fuscia');
insert into suit (id, suit_name, color) values (473, 'Kirlin-Fisher', 'Yellow');
insert into suit (id, suit_name, color) values (474, 'Gerhold, Keebler and Bednar', 'Teal');
insert into suit (id, suit_name, color) values (475, 'Kovacek, Frami and Stanton', 'Fuscia');
insert into suit (id, suit_name, color) values (476, 'Kozey, Tremblay and Buckridge', 'Goldenrod');
insert into suit (id, suit_name, color) values (477, 'Pouros, Mante and Jaskolski', 'Maroon');
insert into suit (id, suit_name, color) values (478, 'Mosciski-Zieme', 'Mauv');
insert into suit (id, suit_name, color) values (479, 'Kunze, Pollich and Wuckert', 'Violet');
insert into suit (id, suit_name, color) values (480, 'Crist, Franecki and Ferry', 'Teal');
insert into suit (id, suit_name, color) values (481, 'Terry-Schneider', 'Fuscia');
insert into suit (id, suit_name, color) values (482, 'Beatty-Schoen', 'Maroon');
insert into suit (id, suit_name, color) values (483, 'Kassulke, Gulgowski and Hoppe', 'Aquamarine');
insert into suit (id, suit_name, color) values (484, 'Stoltenberg Inc', 'Fuscia');
insert into suit (id, suit_name, color) values (485, 'Cremin-Goodwin', 'Puce');
insert into suit (id, suit_name, color) values (486, 'Williamson and Sons', 'Indigo');
insert into suit (id, suit_name, color) values (487, 'Fritsch and Sons', 'Violet');
insert into suit (id, suit_name, color) values (488, 'Towne, Weimann and Cummerata', 'Green');
insert into suit (id, suit_name, color) values (489, 'Oberbrunner-Rau', 'Blue');
insert into suit (id, suit_name, color) values (490, 'Lind, Streich and Purdy', 'Blue');
insert into suit (id, suit_name, color) values (491, 'Blick-Stanton', 'Purple');
insert into suit (id, suit_name, color) values (492, 'Boyer Group', 'Green');
insert into suit (id, suit_name, color) values (493, 'Douglas-Kirlin', 'Blue');
insert into suit (id, suit_name, color) values (494, 'Kutch LLC', 'Aquamarine');
insert into suit (id, suit_name, color) values (495, 'Langworth, Wintheiser and Waters', 'Red');
insert into suit (id, suit_name, color) values (496, 'Lehner Group', 'Puce');
insert into suit (id, suit_name, color) values (497, 'Frami-Leannon', 'Maroon');
insert into suit (id, suit_name, color) values (498, 'Luettgen Group', 'Indigo');
insert into suit (id, suit_name, color) values (499, 'Schmitt, Kreiger and Green', 'Mauv');
insert into suit (id, suit_name, color) values (500, 'Hammes-Howe', 'Blue');
insert into suit (id, suit_name, color) values (501, 'Leffler-Oberbrunner', 'Orange');
insert into suit (id, suit_name, color) values (502, 'Schinner, Labadie and Thiel', 'Crimson');
insert into suit (id, suit_name, color) values (503, 'Labadie and Sons', 'Fuscia');
insert into suit (id, suit_name, color) values (504, 'Nienow-Barton', 'Pink');
insert into suit (id, suit_name, color) values (505, 'Ziemann Group', 'Crimson');
insert into suit (id, suit_name, color) values (506, 'Kautzer Inc', 'Purple');
insert into suit (id, suit_name, color) values (507, 'Ziemann Group', 'Maroon');
insert into suit (id, suit_name, color) values (508, 'Marvin Group', 'Orange');
insert into suit (id, suit_name, color) values (509, 'Ritchie, Boehm and Schoen', 'Maroon');
insert into suit (id, suit_name, color) values (510, 'Langworth, Lemke and Stracke', 'Turquoise');
insert into suit (id, suit_name, color) values (511, 'Thiel, Powlowski and Harvey', 'Puce');
insert into suit (id, suit_name, color) values (512, 'Quigley, Koepp and Daugherty', 'Crimson');
insert into suit (id, suit_name, color) values (513, 'Bosco Group', 'Purple');
insert into suit (id, suit_name, color) values (514, 'Emmerich-Purdy', 'Violet');
insert into suit (id, suit_name, color) values (515, 'Wunsch-Weber', 'Maroon');
insert into suit (id, suit_name, color) values (516, 'Beatty-Heaney', 'Turquoise');
insert into suit (id, suit_name, color) values (517, 'Cremin, Lemke and Reynolds', 'Pink');
insert into suit (id, suit_name, color) values (518, 'Stark, Kuhic and Wuckert', 'Turquoise');
insert into suit (id, suit_name, color) values (519, 'Kessler Group', 'Red');
insert into suit (id, suit_name, color) values (520, 'Hermiston, Kshlerin and Wuckert', 'Khaki');
insert into suit (id, suit_name, color) values (521, 'Parisian, Zemlak and Kilback', 'Yellow');
insert into suit (id, suit_name, color) values (522, 'Stamm and Sons', 'Fuscia');
insert into suit (id, suit_name, color) values (523, 'Lubowitz-Wiegand', 'Violet');
insert into suit (id, suit_name, color) values (524, 'Rutherford, Metz and Gutkowski', 'Purple');
insert into suit (id, suit_name, color) values (525, 'Krajcik, Ortiz and Kozey', 'Violet');
insert into suit (id, suit_name, color) values (526, 'Abernathy and Sons', 'Aquamarine');
insert into suit (id, suit_name, color) values (527, 'Schimmel, Kulas and Jones', 'Pink');
insert into suit (id, suit_name, color) values (528, 'Kunze, Thompson and Parker', 'Indigo');
insert into suit (id, suit_name, color) values (529, 'Pagac LLC', 'Mauv');
insert into suit (id, suit_name, color) values (530, 'Casper-Ebert', 'Aquamarine');
insert into suit (id, suit_name, color) values (531, 'White, Spinka and Sipes', 'Green');
insert into suit (id, suit_name, color) values (532, 'Gottlieb and Sons', 'Teal');
insert into suit (id, suit_name, color) values (533, 'Carter, Gaylord and Kertzmann', 'Khaki');
insert into suit (id, suit_name, color) values (534, 'Dooley LLC', 'Red');
insert into suit (id, suit_name, color) values (535, 'Friesen-Crist', 'Red');
insert into suit (id, suit_name, color) values (536, 'D''Amore, Romaguera and Stroman', 'Red');
insert into suit (id, suit_name, color) values (537, 'Gusikowski-Olson', 'Violet');
insert into suit (id, suit_name, color) values (538, 'MacGyver-Smitham', 'Purple');
insert into suit (id, suit_name, color) values (539, 'Rath-Beatty', 'Teal');
insert into suit (id, suit_name, color) values (540, 'Weber-Swaniawski', 'Maroon');
insert into suit (id, suit_name, color) values (541, 'Klocko-Greenholt', 'Aquamarine');
insert into suit (id, suit_name, color) values (542, 'Keebler and Sons', 'Mauv');
insert into suit (id, suit_name, color) values (543, 'Kunze, Emard and Reichert', 'Turquoise');
insert into suit (id, suit_name, color) values (544, 'Hickle, Auer and Kemmer', 'Crimson');
insert into suit (id, suit_name, color) values (545, 'Hyatt Group', 'Aquamarine');
insert into suit (id, suit_name, color) values (546, 'Ritchie and Sons', 'Indigo');
insert into suit (id, suit_name, color) values (547, 'Cummings and Sons', 'Yellow');
insert into suit (id, suit_name, color) values (548, 'Zboncak-Sanford', 'Pink');
insert into suit (id, suit_name, color) values (549, 'Dicki-Kuhic', 'Khaki');
insert into suit (id, suit_name, color) values (550, 'Bradtke, Senger and Rutherford', 'Crimson');
insert into suit (id, suit_name, color) values (551, 'Block, Streich and Ward', 'Aquamarine');
insert into suit (id, suit_name, color) values (552, 'Bauch LLC', 'Turquoise');
insert into suit (id, suit_name, color) values (553, 'Powlowski, Green and Nienow', 'Indigo');
insert into suit (id, suit_name, color) values (554, 'Pouros Group', 'Pink');
insert into suit (id, suit_name, color) values (555, 'Welch-Murray', 'Khaki');
insert into suit (id, suit_name, color) values (556, 'Russel, Hyatt and Kulas', 'Red');
insert into suit (id, suit_name, color) values (557, 'Davis, Kemmer and Brakus', 'Aquamarine');
insert into suit (id, suit_name, color) values (558, 'Emmerich LLC', 'Puce');
insert into suit (id, suit_name, color) values (559, 'Tillman and Sons', 'Goldenrod');
insert into suit (id, suit_name, color) values (560, 'Koss Group', 'Puce');
insert into suit (id, suit_name, color) values (561, 'Kulas Inc', 'Goldenrod');
insert into suit (id, suit_name, color) values (562, 'Becker-Lockman', 'Turquoise');
insert into suit (id, suit_name, color) values (563, 'Bogan and Sons', 'Blue');
insert into suit (id, suit_name, color) values (564, 'Hackett and Sons', 'Crimson');
insert into suit (id, suit_name, color) values (565, 'Waelchi, Becker and Lesch', 'Blue');
insert into suit (id, suit_name, color) values (566, 'Davis-Wintheiser', 'Indigo');
insert into suit (id, suit_name, color) values (567, 'Torphy-Lakin', 'Goldenrod');
insert into suit (id, suit_name, color) values (568, 'DuBuque-Bogisich', 'Teal');
insert into suit (id, suit_name, color) values (569, 'Leuschke LLC', 'Teal');
insert into suit (id, suit_name, color) values (570, 'Maggio, Grant and Bernhard', 'Fuscia');
insert into suit (id, suit_name, color) values (571, 'Abernathy-Cassin', 'Yellow');
insert into suit (id, suit_name, color) values (572, 'Bayer, Sanford and Beer', 'Goldenrod');
insert into suit (id, suit_name, color) values (573, 'Quigley LLC', 'Turquoise');
insert into suit (id, suit_name, color) values (574, 'O''Kon, Waelchi and Lang', 'Khaki');
insert into suit (id, suit_name, color) values (575, 'Jenkins Inc', 'Orange');
insert into suit (id, suit_name, color) values (576, 'Boyer, Balistreri and Frami', 'Indigo');
insert into suit (id, suit_name, color) values (577, 'Smitham Group', 'Yellow');
insert into suit (id, suit_name, color) values (578, 'Runolfsdottir Group', 'Teal');
insert into suit (id, suit_name, color) values (579, 'Pagac-Graham', 'Red');
insert into suit (id, suit_name, color) values (580, 'Rau-Johnson', 'Mauv');
insert into suit (id, suit_name, color) values (581, 'Carroll-Cummings', 'Teal');
insert into suit (id, suit_name, color) values (582, 'Turcotte-Cartwright', 'Indigo');
insert into suit (id, suit_name, color) values (583, 'Wolff Inc', 'Maroon');
insert into suit (id, suit_name, color) values (584, 'Berge, Dooley and Durgan', 'Fuscia');
insert into suit (id, suit_name, color) values (585, 'Nicolas, Goodwin and Parker', 'Maroon');
insert into suit (id, suit_name, color) values (586, 'Jacobs-Reilly', 'Aquamarine');
insert into suit (id, suit_name, color) values (587, 'Miller-Fritsch', 'Yellow');
insert into suit (id, suit_name, color) values (588, 'Cole-Cartwright', 'Puce');
insert into suit (id, suit_name, color) values (589, 'Jaskolski, Padberg and Blick', 'Green');
insert into suit (id, suit_name, color) values (590, 'Homenick, Grant and Raynor', 'Blue');
insert into suit (id, suit_name, color) values (591, 'Reynolds-Walker', 'Blue');
insert into suit (id, suit_name, color) values (592, 'Bartoletti-Johnston', 'Red');
insert into suit (id, suit_name, color) values (593, 'Ledner-Gleichner', 'Khaki');
insert into suit (id, suit_name, color) values (594, 'Cormier Inc', 'Yellow');
insert into suit (id, suit_name, color) values (595, 'Ortiz Inc', 'Violet');
insert into suit (id, suit_name, color) values (596, 'Schroeder, Hamill and Rau', 'Maroon');
insert into suit (id, suit_name, color) values (597, 'Gutkowski, Gerlach and Kuhlman', 'Teal');
insert into suit (id, suit_name, color) values (598, 'Cole LLC', 'Blue');
insert into suit (id, suit_name, color) values (599, 'Ledner Inc', 'Goldenrod');
insert into suit (id, suit_name, color) values (600, 'Ondricka-Hammes', 'Green');
insert into suit (id, suit_name, color) values (601, 'Cruickshank Group', 'Aquamarine');
insert into suit (id, suit_name, color) values (602, 'Hettinger-Beier', 'Aquamarine');
insert into suit (id, suit_name, color) values (603, 'Heaney, Torphy and Glover', 'Pink');
insert into suit (id, suit_name, color) values (604, 'Orn Inc', 'Fuscia');
insert into suit (id, suit_name, color) values (605, 'Ullrich Group', 'Purple');
insert into suit (id, suit_name, color) values (606, 'Nolan Inc', 'Purple');
insert into suit (id, suit_name, color) values (607, 'Lehner-Feil', 'Purple');
insert into suit (id, suit_name, color) values (608, 'Nienow and Sons', 'Aquamarine');
insert into suit (id, suit_name, color) values (609, 'Hyatt-Wintheiser', 'Crimson');
insert into suit (id, suit_name, color) values (610, 'Langosh, Koch and Corwin', 'Indigo');
insert into suit (id, suit_name, color) values (611, 'Johns Group', 'Blue');
insert into suit (id, suit_name, color) values (612, 'Ondricka and Sons', 'Fuscia');
insert into suit (id, suit_name, color) values (613, 'Bogan, Crona and Jones', 'Khaki');
insert into suit (id, suit_name, color) values (614, 'Runte-Weissnat', 'Khaki');
insert into suit (id, suit_name, color) values (615, 'Hirthe, Hoppe and Crona', 'Fuscia');
insert into suit (id, suit_name, color) values (616, 'Will-Beier', 'Mauv');
insert into suit (id, suit_name, color) values (617, 'Hettinger, Haag and Hartmann', 'Aquamarine');
insert into suit (id, suit_name, color) values (618, 'Borer-Bode', 'Mauv');
insert into suit (id, suit_name, color) values (619, 'Yost and Sons', 'Red');
insert into suit (id, suit_name, color) values (620, 'Cronin Group', 'Green');
insert into suit (id, suit_name, color) values (621, 'Lehner-Gislason', 'Violet');
insert into suit (id, suit_name, color) values (622, 'Huel, Leannon and Tillman', 'Crimson');
insert into suit (id, suit_name, color) values (623, 'Flatley Group', 'Aquamarine');
insert into suit (id, suit_name, color) values (624, 'Paucek-Labadie', 'Khaki');
insert into suit (id, suit_name, color) values (625, 'Leuschke-Torp', 'Yellow');
insert into suit (id, suit_name, color) values (626, 'Brekke-Schulist', 'Yellow');
insert into suit (id, suit_name, color) values (627, 'Wisozk and Sons', 'Puce');
insert into suit (id, suit_name, color) values (628, 'Predovic-McLaughlin', 'Aquamarine');
insert into suit (id, suit_name, color) values (629, 'Nitzsche-Borer', 'Teal');
insert into suit (id, suit_name, color) values (630, 'Auer-Daugherty', 'Puce');
insert into suit (id, suit_name, color) values (631, 'Torp, Funk and Oberbrunner', 'Blue');
insert into suit (id, suit_name, color) values (632, 'Dach Inc', 'Turquoise');
insert into suit (id, suit_name, color) values (633, 'King LLC', 'Maroon');
insert into suit (id, suit_name, color) values (634, 'Collier, Kunde and Renner', 'Teal');
insert into suit (id, suit_name, color) values (635, 'Ullrich LLC', 'Green');
insert into suit (id, suit_name, color) values (636, 'Moore, Deckow and Lynch', 'Goldenrod');
insert into suit (id, suit_name, color) values (637, 'Koss-Rowe', 'Orange');
insert into suit (id, suit_name, color) values (638, 'Runte, Cole and Hagenes', 'Maroon');
insert into suit (id, suit_name, color) values (639, 'Lockman, Zemlak and Ernser', 'Green');
insert into suit (id, suit_name, color) values (640, 'Legros, Torp and Champlin', 'Red');
insert into suit (id, suit_name, color) values (641, 'Treutel, Roob and Hermann', 'Yellow');
insert into suit (id, suit_name, color) values (642, 'Dooley Group', 'Green');
insert into suit (id, suit_name, color) values (643, 'Gutmann LLC', 'Yellow');
insert into suit (id, suit_name, color) values (644, 'Mante, Bayer and Buckridge', 'Orange');
insert into suit (id, suit_name, color) values (645, 'Anderson-Bechtelar', 'Orange');
insert into suit (id, suit_name, color) values (646, 'Cummings, Hand and McKenzie', 'Turquoise');
insert into suit (id, suit_name, color) values (647, 'Heathcote, Smitham and Davis', 'Crimson');
insert into suit (id, suit_name, color) values (648, 'Brown, Koelpin and Vandervort', 'Mauv');
insert into suit (id, suit_name, color) values (649, 'Hills-Graham', 'Red');
insert into suit (id, suit_name, color) values (650, 'Kreiger and Sons', 'Red');
insert into suit (id, suit_name, color) values (651, 'Blick-Luettgen', 'Violet');
insert into suit (id, suit_name, color) values (652, 'Conroy-Gerhold', 'Fuscia');
insert into suit (id, suit_name, color) values (653, 'Hahn-Steuber', 'Yellow');
insert into suit (id, suit_name, color) values (654, 'Hauck-Hahn', 'Indigo');
insert into suit (id, suit_name, color) values (655, 'Smitham Inc', 'Mauv');
insert into suit (id, suit_name, color) values (656, 'Hackett, Metz and Aufderhar', 'Violet');
insert into suit (id, suit_name, color) values (657, 'Streich, Veum and Donnelly', 'Blue');
insert into suit (id, suit_name, color) values (658, 'Corwin, West and Grady', 'Aquamarine');
insert into suit (id, suit_name, color) values (659, 'Wilkinson, Armstrong and Hyatt', 'Yellow');
insert into suit (id, suit_name, color) values (660, 'Mohr Inc', 'Orange');
insert into suit (id, suit_name, color) values (661, 'Kunze, Batz and Farrell', 'Maroon');
insert into suit (id, suit_name, color) values (662, 'Herzog Group', 'Indigo');
insert into suit (id, suit_name, color) values (663, 'Cremin, Marks and Oberbrunner', 'Orange');
insert into suit (id, suit_name, color) values (664, 'Douglas-Ferry', 'Puce');
insert into suit (id, suit_name, color) values (665, 'Klocko, Kirlin and Mosciski', 'Purple');
insert into suit (id, suit_name, color) values (666, 'Hyatt, Zieme and Bashirian', 'Fuscia');
insert into suit (id, suit_name, color) values (667, 'Volkman Inc', 'Purple');
insert into suit (id, suit_name, color) values (668, 'Harvey and Sons', 'Goldenrod');
insert into suit (id, suit_name, color) values (669, 'Hamill, Lockman and Stiedemann', 'Fuscia');
insert into suit (id, suit_name, color) values (670, 'Dare-Ernser', 'Puce');
insert into suit (id, suit_name, color) values (671, 'Kuphal-Kerluke', 'Blue');
insert into suit (id, suit_name, color) values (672, 'Bosco-Langworth', 'Fuscia');
insert into suit (id, suit_name, color) values (673, 'Shields Group', 'Crimson');
insert into suit (id, suit_name, color) values (674, 'Will-Schroeder', 'Puce');
insert into suit (id, suit_name, color) values (675, 'Reichel Group', 'Violet');
insert into suit (id, suit_name, color) values (676, 'Stehr-Nikolaus', 'Pink');
insert into suit (id, suit_name, color) values (677, 'Baumbach Group', 'Violet');
insert into suit (id, suit_name, color) values (678, 'Collins Inc', 'Crimson');
insert into suit (id, suit_name, color) values (679, 'Wisoky Group', 'Red');
insert into suit (id, suit_name, color) values (680, 'Pfeffer LLC', 'Crimson');
insert into suit (id, suit_name, color) values (681, 'Skiles Group', 'Orange');
insert into suit (id, suit_name, color) values (682, 'Upton and Sons', 'Aquamarine');
insert into suit (id, suit_name, color) values (683, 'O''Keefe Group', 'Khaki');
insert into suit (id, suit_name, color) values (684, 'Larson, Leannon and Mitchell', 'Pink');
insert into suit (id, suit_name, color) values (685, 'Mitchell-Marvin', 'Khaki');
insert into suit (id, suit_name, color) values (686, 'Schultz, Ziemann and Schowalter', 'Aquamarine');
insert into suit (id, suit_name, color) values (687, 'Keebler-Smith', 'Maroon');
insert into suit (id, suit_name, color) values (688, 'Howe-Boyle', 'Crimson');
insert into suit (id, suit_name, color) values (689, 'Padberg, Murazik and Pacocha', 'Maroon');
insert into suit (id, suit_name, color) values (690, 'D''Amore Group', 'Blue');
insert into suit (id, suit_name, color) values (691, 'Leuschke, Schmidt and Barrows', 'Blue');
insert into suit (id, suit_name, color) values (692, 'Lebsack, Bahringer and Swift', 'Khaki');
insert into suit (id, suit_name, color) values (693, 'Pfeffer-Little', 'Turquoise');
insert into suit (id, suit_name, color) values (694, 'Mayer and Sons', 'Blue');
insert into suit (id, suit_name, color) values (695, 'Sawayn-Huels', 'Crimson');
insert into suit (id, suit_name, color) values (696, 'Lubowitz, Hills and Glover', 'Orange');
insert into suit (id, suit_name, color) values (697, 'Quitzon, Schultz and Glover', 'Pink');
insert into suit (id, suit_name, color) values (698, 'Wiegand-Goyette', 'Purple');
insert into suit (id, suit_name, color) values (699, 'Block LLC', 'Aquamarine');
insert into suit (id, suit_name, color) values (700, 'Fadel-Littel', 'Purple');
insert into suit (id, suit_name, color) values (701, 'Fisher, Weissnat and Rosenbaum', 'Turquoise');
insert into suit (id, suit_name, color) values (702, 'Walker Group', 'Indigo');
insert into suit (id, suit_name, color) values (703, 'Bergstrom, Gorczany and Sanford', 'Yellow');
insert into suit (id, suit_name, color) values (704, 'Howe Inc', 'Turquoise');
insert into suit (id, suit_name, color) values (705, 'Zboncak and Sons', 'Red');
insert into suit (id, suit_name, color) values (706, 'Lueilwitz, Crona and Spinka', 'Yellow');
insert into suit (id, suit_name, color) values (707, 'Nolan-Christiansen', 'Orange');
insert into suit (id, suit_name, color) values (708, 'Franecki, Sanford and Weissnat', 'Goldenrod');
insert into suit (id, suit_name, color) values (709, 'Beatty Group', 'Aquamarine');
insert into suit (id, suit_name, color) values (710, 'Hagenes LLC', 'Crimson');
insert into suit (id, suit_name, color) values (711, 'Wisozk, Nienow and Hessel', 'Aquamarine');
insert into suit (id, suit_name, color) values (712, 'Bradtke-Douglas', 'Aquamarine');
insert into suit (id, suit_name, color) values (713, 'Wuckert-Turner', 'Crimson');
insert into suit (id, suit_name, color) values (714, 'Goldner, Renner and Huel', 'Maroon');
insert into suit (id, suit_name, color) values (715, 'Rosenbaum LLC', 'Pink');
insert into suit (id, suit_name, color) values (716, 'Jacobs, Collins and Weimann', 'Turquoise');
insert into suit (id, suit_name, color) values (717, 'Daugherty-Zieme', 'Puce');
insert into suit (id, suit_name, color) values (718, 'Hane-Gleason', 'Green');
insert into suit (id, suit_name, color) values (719, 'Ledner, Trantow and Hills', 'Yellow');
insert into suit (id, suit_name, color) values (720, 'Little and Sons', 'Yellow');
insert into suit (id, suit_name, color) values (721, 'Kub, MacGyver and McDermott', 'Turquoise');
insert into suit (id, suit_name, color) values (722, 'Lowe-Lemke', 'Indigo');
insert into suit (id, suit_name, color) values (723, 'Barrows Group', 'Pink');
insert into suit (id, suit_name, color) values (724, 'Considine, Bartoletti and Weissnat', 'Aquamarine');
insert into suit (id, suit_name, color) values (725, 'McCullough Inc', 'Puce');
insert into suit (id, suit_name, color) values (726, 'Abbott Group', 'Turquoise');
insert into suit (id, suit_name, color) values (727, 'Cormier-Frami', 'Indigo');
insert into suit (id, suit_name, color) values (728, 'Ortiz-McLaughlin', 'Maroon');
insert into suit (id, suit_name, color) values (729, 'Greenholt and Sons', 'Crimson');
insert into suit (id, suit_name, color) values (730, 'Bergstrom, D''Amore and Murazik', 'Crimson');
insert into suit (id, suit_name, color) values (731, 'Abernathy, Crooks and Bechtelar', 'Blue');
insert into suit (id, suit_name, color) values (732, 'Maggio-Williamson', 'Aquamarine');
insert into suit (id, suit_name, color) values (733, 'Hartmann Inc', 'Green');
insert into suit (id, suit_name, color) values (734, 'Weber-O''Hara', 'Pink');
insert into suit (id, suit_name, color) values (735, 'Kling, Olson and Fisher', 'Aquamarine');
insert into suit (id, suit_name, color) values (736, 'Considine-Terry', 'Indigo');
insert into suit (id, suit_name, color) values (737, 'Rath, Baumbach and Cronin', 'Maroon');
insert into suit (id, suit_name, color) values (738, 'Satterfield-Von', 'Pink');
insert into suit (id, suit_name, color) values (739, 'Lemke and Sons', 'Orange');
insert into suit (id, suit_name, color) values (740, 'Lubowitz, Jacobson and Erdman', 'Green');
insert into suit (id, suit_name, color) values (741, 'Kunze, Jerde and Leannon', 'Green');
insert into suit (id, suit_name, color) values (742, 'Barrows-Cartwright', 'Khaki');
insert into suit (id, suit_name, color) values (743, 'Jerde-Macejkovic', 'Green');
insert into suit (id, suit_name, color) values (744, 'Roberts, Cassin and Marvin', 'Indigo');
insert into suit (id, suit_name, color) values (745, 'Breitenberg-Schneider', 'Orange');
insert into suit (id, suit_name, color) values (746, 'Fritsch-Beatty', 'Maroon');
insert into suit (id, suit_name, color) values (747, 'Yundt Inc', 'Orange');
insert into suit (id, suit_name, color) values (748, 'Tremblay-Koepp', 'Orange');
insert into suit (id, suit_name, color) values (749, 'Hamill, Ebert and Dickens', 'Red');
insert into suit (id, suit_name, color) values (750, 'Douglas-Rice', 'Violet');
insert into suit (id, suit_name, color) values (751, 'Tremblay, Kutch and Hettinger', 'Yellow');
insert into suit (id, suit_name, color) values (752, 'Boyle Group', 'Green');
insert into suit (id, suit_name, color) values (753, 'Greenholt-Corkery', 'Maroon');
insert into suit (id, suit_name, color) values (754, 'Bradtke, Nitzsche and Rutherford', 'Goldenrod');
insert into suit (id, suit_name, color) values (755, 'Ebert-Zemlak', 'Yellow');
insert into suit (id, suit_name, color) values (756, 'Hayes, Raynor and Murray', 'Indigo');
insert into suit (id, suit_name, color) values (757, 'Fisher-Gerhold', 'Turquoise');
insert into suit (id, suit_name, color) values (758, 'Mitchell, Hansen and Bergstrom', 'Mauv');
insert into suit (id, suit_name, color) values (759, 'Huel, Grant and Ullrich', 'Goldenrod');
insert into suit (id, suit_name, color) values (760, 'McLaughlin, Ledner and Kling', 'Maroon');
insert into suit (id, suit_name, color) values (761, 'Dibbert, Rippin and Simonis', 'Yellow');
insert into suit (id, suit_name, color) values (762, 'Connelly-Hamill', 'Red');
insert into suit (id, suit_name, color) values (763, 'Lebsack-Jenkins', 'Purple');
insert into suit (id, suit_name, color) values (764, 'Bayer-Langosh', 'Yellow');
insert into suit (id, suit_name, color) values (765, 'Thompson, Rath and Halvorson', 'Mauv');
insert into suit (id, suit_name, color) values (766, 'Pouros-Bechtelar', 'Puce');
insert into suit (id, suit_name, color) values (767, 'Abshire, Ebert and Hilpert', 'Indigo');
insert into suit (id, suit_name, color) values (768, 'Wiegand, Erdman and Harvey', 'Aquamarine');
insert into suit (id, suit_name, color) values (769, 'Ledner Inc', 'Green');
insert into suit (id, suit_name, color) values (770, 'Maggio, Upton and Wyman', 'Khaki');
insert into suit (id, suit_name, color) values (771, 'Weissnat Group', 'Purple');
insert into suit (id, suit_name, color) values (772, 'Conroy, Reichel and Barton', 'Fuscia');
insert into suit (id, suit_name, color) values (773, 'Pacocha-Orn', 'Fuscia');
insert into suit (id, suit_name, color) values (774, 'Schiller-Fay', 'Turquoise');
insert into suit (id, suit_name, color) values (775, 'Robel Inc', 'Turquoise');
insert into suit (id, suit_name, color) values (776, 'Larkin LLC', 'Crimson');
insert into suit (id, suit_name, color) values (777, 'Beier-Hudson', 'Yellow');
insert into suit (id, suit_name, color) values (778, 'Watsica-Hyatt', 'Orange');
insert into suit (id, suit_name, color) values (779, 'Bogan, Schowalter and Ebert', 'Fuscia');
insert into suit (id, suit_name, color) values (780, 'Kihn-Collier', 'Khaki');
insert into suit (id, suit_name, color) values (781, 'Pfeffer, Windler and Marks', 'Khaki');
insert into suit (id, suit_name, color) values (782, 'Gleason and Sons', 'Goldenrod');
insert into suit (id, suit_name, color) values (783, 'Graham Group', 'Green');
insert into suit (id, suit_name, color) values (784, 'Schamberger LLC', 'Indigo');
insert into suit (id, suit_name, color) values (785, 'Roberts, Hane and Fay', 'Fuscia');
insert into suit (id, suit_name, color) values (786, 'Lebsack-VonRueden', 'Yellow');
insert into suit (id, suit_name, color) values (787, 'Luettgen, Cassin and MacGyver', 'Khaki');
insert into suit (id, suit_name, color) values (788, 'Rath and Sons', 'Orange');
insert into suit (id, suit_name, color) values (789, 'Gusikowski-Nitzsche', 'Purple');
insert into suit (id, suit_name, color) values (790, 'Crist-Johns', 'Pink');
insert into suit (id, suit_name, color) values (791, 'Baumbach-Kuvalis', 'Crimson');
insert into suit (id, suit_name, color) values (792, 'Hagenes LLC', 'Indigo');
insert into suit (id, suit_name, color) values (793, 'Hand-Ullrich', 'Teal');
insert into suit (id, suit_name, color) values (794, 'Grimes, Kunde and O''Reilly', 'Red');
insert into suit (id, suit_name, color) values (795, 'Rippin Inc', 'Blue');
insert into suit (id, suit_name, color) values (796, 'Deckow and Sons', 'Yellow');
insert into suit (id, suit_name, color) values (797, 'Batz, Lueilwitz and Hudson', 'Goldenrod');
insert into suit (id, suit_name, color) values (798, 'Goldner, Kassulke and Hansen', 'Fuscia');
insert into suit (id, suit_name, color) values (799, 'Smith Inc', 'Khaki');
insert into suit (id, suit_name, color) values (800, 'Runolfsdottir, Wisozk and Feeney', 'Aquamarine');
insert into suit (id, suit_name, color) values (801, 'Reinger Inc', 'Indigo');
insert into suit (id, suit_name, color) values (802, 'Zboncak LLC', 'Blue');
insert into suit (id, suit_name, color) values (803, 'Waelchi, Johnson and Bosco', 'Goldenrod');
insert into suit (id, suit_name, color) values (804, 'Dietrich-Lehner', 'Orange');
insert into suit (id, suit_name, color) values (805, 'Reinger-Brakus', 'Purple');
insert into suit (id, suit_name, color) values (806, 'Goyette, Kuvalis and Harber', 'Purple');
insert into suit (id, suit_name, color) values (807, 'Reinger, Mohr and Zieme', 'Blue');
insert into suit (id, suit_name, color) values (808, 'Stamm, Bergnaum and Koss', 'Puce');
insert into suit (id, suit_name, color) values (809, 'Wuckert-Block', 'Yellow');
insert into suit (id, suit_name, color) values (810, 'Mills-Fahey', 'Fuscia');
insert into suit (id, suit_name, color) values (811, 'Marquardt, Mraz and Morissette', 'Crimson');
insert into suit (id, suit_name, color) values (812, 'Kovacek, D''Amore and Boyer', 'Mauv');
insert into suit (id, suit_name, color) values (813, 'Raynor Inc', 'Red');
insert into suit (id, suit_name, color) values (814, 'Murray, Osinski and Pollich', 'Indigo');
insert into suit (id, suit_name, color) values (815, 'Greenholt-Reichel', 'Violet');
insert into suit (id, suit_name, color) values (816, 'Kutch, Mitchell and Welch', 'Red');
insert into suit (id, suit_name, color) values (817, 'Thompson LLC', 'Turquoise');
insert into suit (id, suit_name, color) values (818, 'Nienow, Moore and Wisoky', 'Blue');
insert into suit (id, suit_name, color) values (819, 'Sawayn, Pouros and Stanton', 'Aquamarine');
insert into suit (id, suit_name, color) values (820, 'Haag, Walker and Dare', 'Indigo');
insert into suit (id, suit_name, color) values (821, 'Fritsch LLC', 'Blue');
insert into suit (id, suit_name, color) values (822, 'Braun, Schowalter and Miller', 'Crimson');
insert into suit (id, suit_name, color) values (823, 'Tromp LLC', 'Puce');
insert into suit (id, suit_name, color) values (824, 'Beahan-Corkery', 'Aquamarine');
insert into suit (id, suit_name, color) values (825, 'Hudson and Sons', 'Red');
insert into suit (id, suit_name, color) values (826, 'Kemmer Inc', 'Fuscia');
insert into suit (id, suit_name, color) values (827, 'Gutkowski-Daugherty', 'Turquoise');
insert into suit (id, suit_name, color) values (828, 'Strosin-O''Connell', 'Indigo');
insert into suit (id, suit_name, color) values (829, 'Miller, Jerde and Feest', 'Mauv');
insert into suit (id, suit_name, color) values (830, 'Reichel-Wuckert', 'Blue');
insert into suit (id, suit_name, color) values (831, 'Bechtelar LLC', 'Mauv');
insert into suit (id, suit_name, color) values (832, 'Glover-Heaney', 'Puce');
insert into suit (id, suit_name, color) values (833, 'Rogahn and Sons', 'Teal');
insert into suit (id, suit_name, color) values (834, 'Connelly and Sons', 'Teal');
insert into suit (id, suit_name, color) values (835, 'Buckridge, Stoltenberg and Metz', 'Fuscia');
insert into suit (id, suit_name, color) values (836, 'Rutherford Inc', 'Pink');
insert into suit (id, suit_name, color) values (837, 'Kovacek-Mraz', 'Mauv');
insert into suit (id, suit_name, color) values (838, 'Kuhn and Sons', 'Teal');
insert into suit (id, suit_name, color) values (839, 'Kemmer, Schaden and Stokes', 'Yellow');
insert into suit (id, suit_name, color) values (840, 'Hettinger-Hammes', 'Yellow');
insert into suit (id, suit_name, color) values (841, 'Russel-Oberbrunner', 'Violet');
insert into suit (id, suit_name, color) values (842, 'Watsica-Casper', 'Yellow');
insert into suit (id, suit_name, color) values (843, 'Quigley, Moen and Brown', 'Red');
insert into suit (id, suit_name, color) values (844, 'Krajcik-Kirlin', 'Yellow');
insert into suit (id, suit_name, color) values (845, 'Wiegand-Mitchell', 'Indigo');
insert into suit (id, suit_name, color) values (846, 'Funk, Hane and Boehm', 'Khaki');
insert into suit (id, suit_name, color) values (847, 'Moore Group', 'Blue');
insert into suit (id, suit_name, color) values (848, 'Swaniawski-Kassulke', 'Orange');
insert into suit (id, suit_name, color) values (849, 'Thompson Group', 'Crimson');
insert into suit (id, suit_name, color) values (850, 'Lang-Ondricka', 'Puce');
insert into suit (id, suit_name, color) values (851, 'Mohr-Greenfelder', 'Goldenrod');
insert into suit (id, suit_name, color) values (852, 'Satterfield, Bahringer and Mraz', 'Turquoise');
insert into suit (id, suit_name, color) values (853, 'Monahan-Jacobs', 'Maroon');
insert into suit (id, suit_name, color) values (854, 'Trantow LLC', 'Blue');
insert into suit (id, suit_name, color) values (855, 'Kohler Inc', 'Fuscia');
insert into suit (id, suit_name, color) values (856, 'Greenfelder LLC', 'Indigo');
insert into suit (id, suit_name, color) values (857, 'Hahn-Monahan', 'Blue');
insert into suit (id, suit_name, color) values (858, 'Flatley, Collier and Breitenberg', 'Mauv');
insert into suit (id, suit_name, color) values (859, 'Rodriguez-Rempel', 'Pink');
insert into suit (id, suit_name, color) values (860, 'Schuppe-Nienow', 'Indigo');
insert into suit (id, suit_name, color) values (861, 'Vandervort-Powlowski', 'Green');
insert into suit (id, suit_name, color) values (862, 'Herzog, Mayer and Bednar', 'Maroon');
insert into suit (id, suit_name, color) values (863, 'Kohler Group', 'Pink');
insert into suit (id, suit_name, color) values (864, 'Hickle-Halvorson', 'Teal');
insert into suit (id, suit_name, color) values (865, 'Schmeler, Rice and Dach', 'Aquamarine');
insert into suit (id, suit_name, color) values (866, 'Lehner-Stanton', 'Red');
insert into suit (id, suit_name, color) values (867, 'Turcotte, Sipes and Spinka', 'Crimson');
insert into suit (id, suit_name, color) values (868, 'Toy, O''Kon and Schaefer', 'Blue');
insert into suit (id, suit_name, color) values (869, 'Ernser-Ondricka', 'Violet');
insert into suit (id, suit_name, color) values (870, 'Will, Kohler and Koepp', 'Green');
insert into suit (id, suit_name, color) values (871, 'Conn, Bogisich and Denesik', 'Blue');
insert into suit (id, suit_name, color) values (872, 'Cassin Inc', 'Maroon');
insert into suit (id, suit_name, color) values (873, 'Ratke, Tillman and Sawayn', 'Goldenrod');
insert into suit (id, suit_name, color) values (874, 'Lockman, Abernathy and Terry', 'Crimson');
insert into suit (id, suit_name, color) values (875, 'O''Connell-Dibbert', 'Yellow');
insert into suit (id, suit_name, color) values (876, 'Beer Inc', 'Teal');
insert into suit (id, suit_name, color) values (877, 'Kovacek-Connelly', 'Green');
insert into suit (id, suit_name, color) values (878, 'Price and Sons', 'Violet');
insert into suit (id, suit_name, color) values (879, 'Kreiger-Nader', 'Mauv');
insert into suit (id, suit_name, color) values (880, 'Kessler-Fay', 'Fuscia');
insert into suit (id, suit_name, color) values (881, 'Cole, Halvorson and Schultz', 'Turquoise');
insert into suit (id, suit_name, color) values (882, 'Cassin Group', 'Orange');
insert into suit (id, suit_name, color) values (883, 'Treutel Inc', 'Orange');
insert into suit (id, suit_name, color) values (884, 'Nicolas, King and Stroman', 'Violet');
insert into suit (id, suit_name, color) values (885, 'Lemke, Reichert and Nicolas', 'Mauv');
insert into suit (id, suit_name, color) values (886, 'Kertzmann, Spencer and Nolan', 'Maroon');
insert into suit (id, suit_name, color) values (887, 'Brekke LLC', 'Blue');
insert into suit (id, suit_name, color) values (888, 'Rolfson Inc', 'Puce');
insert into suit (id, suit_name, color) values (889, 'Barrows Group', 'Green');
insert into suit (id, suit_name, color) values (890, 'Lowe Group', 'Fuscia');
insert into suit (id, suit_name, color) values (891, 'Green, Towne and Ondricka', 'Fuscia');
insert into suit (id, suit_name, color) values (892, 'Wisozk-Bergnaum', 'Violet');
insert into suit (id, suit_name, color) values (893, 'Rempel-Gulgowski', 'Red');
insert into suit (id, suit_name, color) values (894, 'Lemke-Schaden', 'Mauv');
insert into suit (id, suit_name, color) values (895, 'Langosh-Koepp', 'Turquoise');
insert into suit (id, suit_name, color) values (896, 'Cartwright, Koelpin and Lind', 'Orange');
insert into suit (id, suit_name, color) values (897, 'Paucek, Witting and Kling', 'Maroon');
insert into suit (id, suit_name, color) values (898, 'Tremblay Group', 'Crimson');
insert into suit (id, suit_name, color) values (899, 'Bahringer Group', 'Pink');
insert into suit (id, suit_name, color) values (900, 'Wisoky-Bartoletti', 'Fuscia');
insert into suit (id, suit_name, color) values (901, 'Greenfelder-Weber', 'Goldenrod');
insert into suit (id, suit_name, color) values (902, 'Pouros, Schamberger and Bashirian', 'Green');
insert into suit (id, suit_name, color) values (903, 'Bosco-Glover', 'Red');
insert into suit (id, suit_name, color) values (904, 'Rau-Sipes', 'Violet');
insert into suit (id, suit_name, color) values (905, 'Leffler, Terry and Wilderman', 'Aquamarine');
insert into suit (id, suit_name, color) values (906, 'Rutherford, Pagac and Padberg', 'Red');
insert into suit (id, suit_name, color) values (907, 'Weber, Hegmann and Kutch', 'Crimson');
insert into suit (id, suit_name, color) values (908, 'Hudson-Auer', 'Mauv');
insert into suit (id, suit_name, color) values (909, 'Kirlin and Sons', 'Crimson');
insert into suit (id, suit_name, color) values (910, 'Gusikowski LLC', 'Goldenrod');
insert into suit (id, suit_name, color) values (911, 'Kessler-Wintheiser', 'Pink');
insert into suit (id, suit_name, color) values (912, 'Price, Howe and Graham', 'Red');
insert into suit (id, suit_name, color) values (913, 'Thompson, McDermott and Schinner', 'Turquoise');
insert into suit (id, suit_name, color) values (914, 'Bode, Kiehn and Torphy', 'Pink');
insert into suit (id, suit_name, color) values (915, 'Bergstrom Group', 'Khaki');
insert into suit (id, suit_name, color) values (916, 'Littel, Corkery and Bayer', 'Khaki');
insert into suit (id, suit_name, color) values (917, 'Waelchi-Douglas', 'Blue');
insert into suit (id, suit_name, color) values (918, 'Von and Sons', 'Turquoise');
insert into suit (id, suit_name, color) values (919, 'Considine Group', 'Purple');
insert into suit (id, suit_name, color) values (920, 'Nader, Balistreri and Moore', 'Orange');
insert into suit (id, suit_name, color) values (921, 'Hickle-Metz', 'Indigo');
insert into suit (id, suit_name, color) values (922, 'Zieme LLC', 'Khaki');
insert into suit (id, suit_name, color) values (923, 'Wiza Inc', 'Maroon');
insert into suit (id, suit_name, color) values (924, 'Hayes LLC', 'Puce');
insert into suit (id, suit_name, color) values (925, 'Bradtke, Klein and O''Conner', 'Orange');
insert into suit (id, suit_name, color) values (926, 'Pfannerstill-Boyle', 'Purple');
insert into suit (id, suit_name, color) values (927, 'Jenkins LLC', 'Aquamarine');
insert into suit (id, suit_name, color) values (928, 'Rice Group', 'Green');
insert into suit (id, suit_name, color) values (929, 'Toy LLC', 'Blue');
insert into suit (id, suit_name, color) values (930, 'Hayes, Shanahan and Jerde', 'Red');
insert into suit (id, suit_name, color) values (931, 'Yost, Leffler and Zboncak', 'Mauv');
insert into suit (id, suit_name, color) values (932, 'Gusikowski Inc', 'Turquoise');
insert into suit (id, suit_name, color) values (933, 'Waelchi, Murray and Boehm', 'Orange');
insert into suit (id, suit_name, color) values (934, 'Rolfson, Hegmann and Marquardt', 'Yellow');
insert into suit (id, suit_name, color) values (935, 'Frami, Prohaska and Tillman', 'Red');
insert into suit (id, suit_name, color) values (936, 'Bergstrom, Schulist and Dach', 'Goldenrod');
insert into suit (id, suit_name, color) values (937, 'Streich Group', 'Purple');
insert into suit (id, suit_name, color) values (938, 'Koch Group', 'Red');
insert into suit (id, suit_name, color) values (939, 'Hagenes-Ziemann', 'Maroon');
insert into suit (id, suit_name, color) values (940, 'Wehner, Will and Mann', 'Yellow');
insert into suit (id, suit_name, color) values (941, 'Rosenbaum and Sons', 'Indigo');
insert into suit (id, suit_name, color) values (942, 'Haley, Rice and Bergstrom', 'Blue');
insert into suit (id, suit_name, color) values (943, 'Swift Group', 'Indigo');
insert into suit (id, suit_name, color) values (944, 'Bergstrom-Gibson', 'Khaki');
insert into suit (id, suit_name, color) values (945, 'Moen-DuBuque', 'Indigo');
insert into suit (id, suit_name, color) values (946, 'Gutmann, Kub and Stamm', 'Crimson');
insert into suit (id, suit_name, color) values (947, 'Reynolds, Purdy and Heaney', 'Khaki');
insert into suit (id, suit_name, color) values (948, 'Bashirian-Schmeler', 'Indigo');
insert into suit (id, suit_name, color) values (949, 'Hoeger, Rempel and Renner', 'Crimson');
insert into suit (id, suit_name, color) values (950, 'VonRueden, Pfeffer and Effertz', 'Crimson');
insert into suit (id, suit_name, color) values (951, 'Ratke-Kreiger', 'Maroon');
insert into suit (id, suit_name, color) values (952, 'Connelly, Jacobi and Beatty', 'Red');
insert into suit (id, suit_name, color) values (953, 'Wisoky, Hayes and Witting', 'Maroon');
insert into suit (id, suit_name, color) values (954, 'Roberts, Shanahan and Rutherford', 'Teal');
insert into suit (id, suit_name, color) values (955, 'Dare-Corwin', 'Violet');
insert into suit (id, suit_name, color) values (956, 'Dickinson, Bode and Wiegand', 'Fuscia');
insert into suit (id, suit_name, color) values (957, 'Bailey-Block', 'Goldenrod');
insert into suit (id, suit_name, color) values (958, 'Bednar-Schamberger', 'Crimson');
insert into suit (id, suit_name, color) values (959, 'Ritchie Group', 'Turquoise');
insert into suit (id, suit_name, color) values (960, 'Ortiz Inc', 'Goldenrod');
insert into suit (id, suit_name, color) values (961, 'Stamm Inc', 'Orange');
insert into suit (id, suit_name, color) values (962, 'Feeney Group', 'Yellow');
insert into suit (id, suit_name, color) values (963, 'Cartwright Inc', 'Indigo');
insert into suit (id, suit_name, color) values (964, 'Gislason-Braun', 'Pink');
insert into suit (id, suit_name, color) values (965, 'Jones, Torp and Carter', 'Crimson');
insert into suit (id, suit_name, color) values (966, 'Toy-Bauch', 'Khaki');
insert into suit (id, suit_name, color) values (967, 'Walter Inc', 'Maroon');
insert into suit (id, suit_name, color) values (968, 'Stamm-Kunze', 'Maroon');
insert into suit (id, suit_name, color) values (969, 'Lindgren, Jacobs and Sanford', 'Yellow');
insert into suit (id, suit_name, color) values (970, 'Rowe and Sons', 'Teal');
insert into suit (id, suit_name, color) values (971, 'Harber, Kerluke and Lindgren', 'Teal');
insert into suit (id, suit_name, color) values (972, 'Morar-Walker', 'Teal');
insert into suit (id, suit_name, color) values (973, 'Schowalter, Kessler and Armstrong', 'Maroon');
insert into suit (id, suit_name, color) values (974, 'Vandervort Group', 'Green');
insert into suit (id, suit_name, color) values (975, 'Kreiger, Marks and Green', 'Yellow');
insert into suit (id, suit_name, color) values (976, 'Lockman, Douglas and Roberts', 'Red');
insert into suit (id, suit_name, color) values (977, 'DuBuque-Hane', 'Crimson');
insert into suit (id, suit_name, color) values (978, 'Thiel Inc', 'Fuscia');
insert into suit (id, suit_name, color) values (979, 'Lang Inc', 'Teal');
insert into suit (id, suit_name, color) values (980, 'Hoeger-Hilpert', 'Yellow');
insert into suit (id, suit_name, color) values (981, 'Yost-Haley', 'Mauv');
insert into suit (id, suit_name, color) values (982, 'Gorczany, Crooks and Marks', 'Yellow');
insert into suit (id, suit_name, color) values (983, 'Heller-Hartmann', 'Indigo');
insert into suit (id, suit_name, color) values (984, 'Daugherty LLC', 'Maroon');
insert into suit (id, suit_name, color) values (985, 'Bayer, Little and Ryan', 'Khaki');
insert into suit (id, suit_name, color) values (986, 'Howell and Sons', 'Crimson');
insert into suit (id, suit_name, color) values (987, 'Gusikowski-McGlynn', 'Khaki');
insert into suit (id, suit_name, color) values (988, 'Shanahan, Steuber and Koepp', 'Turquoise');
insert into suit (id, suit_name, color) values (989, 'Kling-Ebert', 'Violet');
insert into suit (id, suit_name, color) values (990, 'Raynor-Hayes', 'Goldenrod');
insert into suit (id, suit_name, color) values (991, 'Parisian and Sons', 'Khaki');
insert into suit (id, suit_name, color) values (992, 'Olson-Hermiston', 'Yellow');
insert into suit (id, suit_name, color) values (993, 'Gusikowski-Rohan', 'Purple');
insert into suit (id, suit_name, color) values (994, 'Effertz-Swift', 'Fuscia');
insert into suit (id, suit_name, color) values (995, 'Green and Sons', 'Turquoise');
insert into suit (id, suit_name, color) values (996, 'Kulas LLC', 'Puce');
insert into suit (id, suit_name, color) values (997, 'Abbott-Mante', 'Indigo');
insert into suit (id, suit_name, color) values (998, 'Wintheiser, Kihn and Bailey', 'Green');
insert into suit (id, suit_name, color) values (999, 'Murazik Group', 'Blue');
insert into suit (id, suit_name, color) values (1000, 'Schultz, Vandervort and Lesch', 'Maroon');
